apiVersion: V1
kind: Pod
metadata: 
    name: myapp-pod
    labels:
          app: myapp
spec:
    containers
    - name: nginx-container
      image: nginx

# Command to create pod from this definition file
# Kubectl create -f Create-POD.yaml
